-- ========================================
-- DEPRECATED: video_servers (replaced by embed/download fields in public.videos)
-- ========================================
--
-- Pada DB v2:
-- - `public.video_servers` dihapus
-- - embed/download disimpan langsung di `public.videos`:
--   embed_url_turbovip_480 / embed_url_turbovip_720
--   embed_url_filedon_480 / embed_url_filedon_720
--   download_url_turbovip_480 / download_url_turbovip_720
--   download_url_filedon_480 / download_url_filedon_720
--
-- Contoh update episode (edit ID & URL Anda):
-- UPDATE public.videos
-- SET
--   embed_url_turbovip_480 = 'https://...embed...',
--   embed_url_turbovip_720 = 'https://...embed...',
--   embed_url_filedon_480 = 'https://...embed...',
--   embed_url_filedon_720 = 'https://...embed...',
--   download_url_turbovip_480 = 'https://...download...',
--   download_url_turbovip_720 = 'https://...download...',
--   download_url_filedon_480 = 'https://...download...',
--   download_url_filedon_720 = 'https://...download...'
-- WHERE id = 'VIDEO_OR_EPISODE_ID';

-- RLS untuk `public.videos` sudah diatur di `supabase-rls-setup.sql`.
